assets:
    js: []
    css: []
    js_prod_assets: []
    js_prod: []

modules:
    sparkleModule:
        files:
            - bundles/os2displaysparklefeed/apps/sparkle/module.js
            - bundles/os2displaysparklefeed/apps/sparkle/sparkle.js

apps:
    ikApp:
        dependencies:
            - sparkleModule
